import type { Metadata } from 'next'
import './globals.css'
import NextUiProvider from '@/providers/NextuiProvider'
import TopNavigation from '@/components/ui/TopNavigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark'>
        <NextUiProvider>
          <div className='w-full h-screen overflow-hidden grid grid-cols-1 grid-rows-[max-content_1fr] dark:bg-black bg-gray-50'>
            <TopNavigation />

            <div className='overflow-y-auto '>
              {children}
            </div>
          </div>
        </NextUiProvider>
      </body>
    </html>
  )
}
